apiVersion: v1
kind: Pod
metadata:
  labels:
    app: echo
  name: pod-hello-world
  namespace: default
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    imagePullPolicy: IfNotPresent
    name: hello-world
